# Preprocessing Phase
- This phase will cover the cleaning of dataset for use in modelling.
- Since I decided not to drop rows with null values because they have other important metric present like `demand_count` etc, I will split the dataset into two samples, one cleaned (for modelling) and one with its original structure for visualizations.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Import
DATASET_FILEPATH = '../../dataset/raw/'
DATASET_FILENAME = 'skill-scarcity-index.csv'
FIGURES_FILEPATH = '../../figures'

# Pandas import
df = pd.read_csv(DATASET_FILEPATH+DATASET_FILENAME, index_col=0).reset_index(drop=True)

In [7]:
# First 10 Rows
df.head(10)

,category,skill_name,demand_count,demand_pct,median_days_open,salary_premium_pct,repost_rate_pct,scarcity_score
0,ai,A/B Testing,115,4.7,1.0,3.9,2.0,49.2
1,ai,Agile / Scrum,63,2.6,1.0,42.5,14.0,62.9
2,ai,AI Agents,153,6.3,NaN,45.5,5.9,72.0
3,ai,AI Coding Tools,32,1.3,NaN,NaN,0.0,0.0
4,ai,Airflow,54,2.2,9.0,-38.7,16.2,57.2
5,ai,AWS,259,10.6,0.0,-29.2,11.2,31.0
6,ai,Azure,221,9.0,0.0,-46.9,19.5,28.3
7,ai,BigQuery,43,1.8,4.0,NaN,22.2,75.5
8,ai,C#,42,1.7,0.0,-31.5,7.2,25.0
9,ai,C++,66,2.7,1.0,-10.9,18.0,60.4

In [9]:
# Function for imputing missing values from columns using median
def impute_median(df, column):
    df[f"{column}_missing"] = df[column].isna()
    df[column] = df[column].fillna(df.groupby("category")[column].transform("median"))
    df[column] = df[column].fillna(df[column].median())

In [10]:
# Call function for each column
missing_cols = ["median_days_open", "salary_premium_pct"]
for col in missing_cols:
    impute_median(df, col)

In [11]:
# Show rows that have null values in the 'median_days_open' column
null_median_days = df[df['median_days_open'].isnull()]
print(f"Number of rows with Null Values: {len(null_median_days)}")
null_median_days

Number of rows with Null Values: 0

Empty DataFrame
Columns: [category, skill_name, demand_count, demand_pct, median_days_open, salary_premium_pct, repost_rate_pct, scarcity_score, median_days_open_missing, salary_premium_pct_missing]
Index: []

In [12]:
# Show rows that have null values in the 'salary_premium_pct' 
null_salary_premium_pct = df[df['salary_premium_pct'].isnull()]
print(f"Number of rows with Null Values: {len(null_salary_premium_pct)}")
null_salary_premium_pct

Number of rows with Null Values: 0

Empty DataFrame
Columns: [category, skill_name, demand_count, demand_pct, median_days_open, salary_premium_pct, repost_rate_pct, scarcity_score, median_days_open_missing, salary_premium_pct_missing]
Index: []